export const GET_DATA_REQ = "GET_DATA_REQ";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const SEARCH_TERM = "SEARCH_TERM";

export const PAGE_CHANGED = "PAGE_CHANGED";

export const ITEM_CHECKED = "ITEM_CHECKED";
export const ITEM_UNCHECKED = "ITEM_UNCHECKED";
export const DELETE_SELECTED = "DELETE_SELECTED";

export const SET_ALL_SELECT_PAGE_NO='SET_ALL_SELECT_PAGE_NO'
export const START_EDITABLE='START_EDITABLE'
export const END_EDITABLE='END_EDITABLE'

